parameters:
  name: ''
  queue: ''
  displayName: ''
  platform: ''
  arch: 'x64' # Only overriden by 32-bit Windows
  configuration: 'Release' # Only do debug if specified

phases:
- phase: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  queue: ${{ parameters.queue }}
  steps:
  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/City.Chain.csproj'
      workingDirectory: 'src/City.Chain'
      #arguments: ${{ format('-c {0} -r {1}-{2} -v m', parameters.configuration, parameters.platform, parameters.arch) }}
