parameters:
  name: ''
  queue: ''
  displayName: ''
  platform: ''
  arch: 'x64' # Only overriden by 32-bit Windows
  configuration: 'Release' # Only do debug if specified

phases:
- phase: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  queue: ${{ parameters.queue }}
  steps:

  - powershell: |
      $version = (Get-Content package.json) -join "`n" | ConvertFrom-Json | Select -ExpandProperty "version"
      Write-Host "##vso[task.setvariable variable=Build.BuildNumber]$version"
      Write-Host "##vso[task.setvariable variable=App.BuildNumber]$version" 
      Write-Host "##vso[task.setvariable variable=App.Configuration]$parameters.configuration" 
      Write-Host "##vso[task.setvariable variable=App.Platform]$parameters.platform" 
      Write-Host "##vso[task.setvariable variable=App.Arch]$parameters.arch" 
    displayName: Get Version Number

  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: publish
      projects: '**/City.Chain.csproj'
      workingDirectory: 'src/City.Chain'
      publishWebProjects: false
      zipAfterPublish: false
      modifyOutputPath: false
      arguments: ${{ format('-c {0} -r {1}-{2} -v m', parameters.configuration, parameters.platform, parameters.arch) }}

  - task: ArchiveFiles@2
    displayName: Archive src/City.Chain/bin/Release/netcoreapp2.1/publish/
    inputs:
      rootFolderOrFile: ${{ format('src/City.Chain/bin/{0}/netcoreapp2.1/{1}-{2}/publish/', parameters.configuration, parameters.platform, parameters.arch) }}
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/City.Chain-$(App.BuildNumber)-$(App.Arch)-$(App.Configuration)-$(App.Platform).zip'

  - task: marcelo-formentao.github-tools.github-release-publish-task.GitHubReleasePublish@0
    displayName: Create or Modify GitHub Release
    inputs:
      githubEndpoint: github
      githubRepository: 'CityChainFoundation/city-chain'
      githubReleaseTitle: 'City Chain $(Build.BuildNumber) (Preview Release)'
      githubReleasePrerelease: true
      githubReleaseAsset: '$(Build.ArtifactStagingDirectory)/City.Chain*.zip'
      manifestJson: package.json
      githubEditRelease: true
