parameters:
  name: ''
  queue: ''
  displayName: ''
  platform: ''
  arch: 'x64' # Only overriden by 32-bit Windows
  configuration: 'Release' # Only do debug if specified

phases:
- phase: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  queue: ${{ parameters.queue }}
  steps:
  # - script: ${{ format('echo {0}', parameters.arch) }}
  # - script: ${{ format('echo {0}', parameters.arch) }}
  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: publish
      arguments: ${{ format('src/City.Chain/City.Chain.csproj -c {0} -r {1}-{2} -v m', parameters.configuration, parameters.platform, parameters.arch) }}
      #workingDirectory: 'src/City.Chain/City.Chain.csproj'
