parameters:
  name: ''
  queue: ''
  displayName: ''
  platform: ''
  arch: 'x64' # Only overriden by 32-bit Windows
  configuration: 'Release' # Only do debug if specified

phases:
- phase: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  queue: ${{ parameters.queue }}
  steps:
  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    env: 
      buildConfiguration: ${{ parameters.configuration }}
      buildPlatform: ${{ parameters.platform }}
      buildArchitecture: ${{ parameters.arch }}
    inputs:
      command: publish
      arguments: '-c %buildConfiguration% -r %buildPlatform%-%buildArchitecture% -v m'
      workingDirectory: 'src/City.Chain'
