version: '2'
services:
  nako:
    container_name: city-nako
    restart: always
    networks: 
        - nakonet
    image: coinvault/nako-indexer:latest
    command: city RpcDomain="{CoinTag}-client" RpcAccessPort=5000 ConnectionString="mongodb://{CoinTag}-mongo" DatabaseNameSubfix="false" NetworkWitnessPrefix="city" StoreRawTransactions="true"
    ports: 
        - 80:9000
        - 443:9000
        - 9019:9000
    depends_on:
        - mongo
        - client
  client:
    container_name: city-client
    restart: always
    networks: 
        - nakonet
    image: citychain/citychain:1.0.21
    command: ["-server=1", "-rpcallowip=172.16.10.0/24", "-rpcbind=city-client", "apiuri=http://0.0.0.0:4335/", "-rpcport=5000", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword", "-txindex=1"]
    ports: 
        - 5019:5000
  mongo:
    container_name: city-mongo
    restart: always
    networks: 
        - nakonet
    image: mongo:3.2
networks:
  nakonet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/24