apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-explorer.yml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  ports:
  - name: "5030"
    port: 5030
    targetPort: 5000
  - name: "16178"
    port: 16178
    targetPort: 16178
  selector:
    io.kompose.service: client
status:
  loadBalancer: {}
