name: Build

on: 
  push:
    branches:
      - feature/*

jobs:
  
  buildTestRelease:

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        node_version: [12.x]
        dotnet_version: ['2.1.607', '2.1.x', '2.2']
      fail-fast: false

    runs-on: ${{ matrix.os }}
    
    env:
      SOLUTION_PATH: 'src/City.Chain.sln'
      BUILD_CONFIGURATION: 'Release'

    steps:

    - uses: actions/checkout@v1'
      name: Checkout

    - name: Setup Node.js (${{ matrix.node_version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Version
      id: setversion
      run: |
        echo ::set-env name=VERSION::$(npm run version --silent)

    - name: Setup .NET Core (${{ matrix.dotnet_version }})
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet_version }}

    - name: Restore
      run: dotnet restore ${{env.SOLUTION_PATH}}
      
    - name: Build
      run: dotnet build --configuration ${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_PATH}}
      
#    - name: Unit Test
#      run: dotnet test -v=normal --no-build --filter FullyQualifiedName!~IntegrationTests --configuration ${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_PATH}}

    - uses: "marvinpinto/action-automatic-releases@latest"
      name: "Release"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{env.VERSION}}"
        prerelease: true
        draft: true
        title: "City Chain (Release ${{env.VERSION}})"
        files: |
          LICENSE
          package.json